language: java
jdk:
        -openjdk11
        
addons:
    sonarcloud:
        organization: kevinmoreland
        token: f3c4e529909ec4a0347b81291ff282b73cc33e37
script: 
- ant build
- sonar-scanner